source "https://rubygems.org"

ruby "3.1.2"

gem "rails", "~> 7.1.6"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]
gem "bootsnap", require: false

# Auth
gem "devise"
gem "devise-jwt"

# CORS
gem "rack-cors"

# JSON serialization
gem "jsonapi-serializer"

# AI
gem "anthropic"

# Environment variables
gem "dotenv-rails", groups: [:development, :test]

group :development, :test do
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end

group :development do
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
end

group :test do
  gem "shoulda-matchers"
  gem "database_cleaner-active_record"
end
